In [1]:
import pandas as pd
import glob

In [2]:
#caminho da leitura
path = r'D:\Dropbox\Pessoal\Python\COVID\COVID19-SP-BR\Dados'
files = glob.glob(path + "/*.xlsx")

In [3]:
#Importação do dataframe padrao
df = pd.read_excel(r"D:\Dropbox\Pessoal\Python\COVID\COVID19-SP-BR\tabelas_analise\tabela_base.xlsx", index_col=0)

In [4]:
df.head()

,26_mar,27_mar,28_mar,29_mar,30_mar,01_abr,02_abr,03_abr,04_abr,05_abr,...,26-jun,27-jun,28-jun,29-jun,30-jun,01-jul,02-jul,03-jul,04-jul,05-jul
adamantina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adolfo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
aguai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
aguas da prata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
aguas de lindoia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#Para cada coluna do DF padrão procura a correnpondência no arquivo de dados e adiciona onde houver correspondência entre
# o nome do arquivo e a coluna padrão assim como onde o nome da cidade for semelhante entre os dois

# iterando entre as colunas
for col in list(df.columns):
    
    #iterando entre os arquivos
    for file in files:
        f = pd.read_excel(file, index_col=0, header= None)
        
        #criação de um dicionário para armazenar o valor e a chave
        d = dict(f[1])
        
        #verificando se o nome do arquivo tem correspondência com alguma coluna
        if file.rpartition('\\')[2].replace(".xlsx", "") == col:
            
            # se houver itera entre as chaves do dicionário e adiciona o valor dele na coluna do DF padrão
            for i in d:
                try:
                    df.loc[i, col] = d.get(i)
                except:
                    continue

In [6]:
df.fillna(0, inplace = True)

In [7]:
df.to_csv(r"D:\Dropbox\Pessoal\Python\COVID\COVID19-SP-BR\tabelas_analise\infectados_municipio.csv")

In [8]:
df.columns

Index(['26_mar', '27_mar', '28_mar', '29_mar', '30_mar', '01_abr', '02_abr',
       '03_abr', '04_abr', '05_abr',
       ...
       '26-jun', '27-jun', '28-jun', '29-jun', '30-jun', '01-jul', '02-jul',
       '03-jul', '04-jul', '05-jul'],
      dtype='object', length=101)